"""added weight table

Revision ID: d22857065e46
Revises: acf10c8e3bb2
Create Date: 2024-12-09 21:40:25.602753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd22857065e46'
down_revision = 'acf10c8e3bb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['date_id'], ['dates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weights')
    # ### end Alembic commands ###
